"""Issue 366: scope items lost their confirmation on any SQL edit because they have no location.

Three failure modes from #366 and its comments, each driven through the real sqlreview.sh:

* A scope revision after an SQL edit re-asked every unchanged `location: null` item. A scope item
  states intent, not SQL lines, so identical id/list/text/rationale carries it (basis
  ``intent-unchanged``); publish still proves the claim and records ``carried_basis``.
* Scope-first (``sql_sha256: null``, the recommended order): analyse's ``carryover`` walked every
  item once the SQL existed. Matching items now come back in ``carry_over_intent``
  (``scope-before-sql``) with their new location, for one bulk answer.
* A comment-only commit copied the scope into the SQL ``/* ... */`` header, so the raw SHA changed
  and nothing carried. Only the LEADING comment header is now ignored (``sql-body-unchanged``); the
  rest of the file is compared byte for byte, and anything odd in the header fails closed.

Review items with ``location: null`` do NOT carry silently after a real SQL change: they are
offered for one bulk question (``bulk``, with their location), and publish still refuses them.

Why the existing tests missed these: ``test_sql_review_carryover`` pinned "nothing carries" for a
scope without ``sql_sha256`` (the scope-first shape), and ``test_sql_review_carryforward`` used
``LINE_SHIFT`` (a prepended ``--`` comment, i.e. a comment-only change) as its "SQL changed" fixture.
"""
import hashlib
import json
import os
import stat
import tempfile
import unittest
from pathlib import Path

try:  # `unittest discover -s tests` puts tests/ on sys.path; `-m unittest tests.x` does not
    from test_sql_review_scripts import REPO, SQL_V1, Project, item, review_doc, run, scope_doc
except ModuleNotFoundError:
    from tests.test_sql_review_scripts import REPO, SQL_V1, Project, item, review_doc, run, scope_doc

# SQL_V1, numbered:
#   1 WITH stays AS (            4 )                          7 GROUP BY month;
#   2   SELECT * FROM adm.stays  5 SELECT month, COUNT(*) AS n
#   3   WHERE discharge_date ... 6 FROM stays
CODE_EDIT = SQL_V1.replace("adm.stays", "adm.stays_v2")                  # line 2, executable
HEADER = ("/*\nassumptions:\n  - Only completed stays\n    rationale: Open stays lack a discharge date.\n"
          "limitations:\n  - Monthly grain only\n    consequence: Source has no daily data.\n*/\n")
HEADER_ONLY = HEADER + "-- generated by query-builder\n\n" + SQL_V1     # only the leading header changed
N = HEADER_ONLY.count("\n") - SQL_V1.count("\n")                        # lines the header added

WHO = {"confirmed_by": "analyst@example", "confirmed_at": "2026-09-15T00:00:00Z"}


def sha(text):
    return hashlib.sha256(text.encode()).hexdigest()


def scope_items(revision=1):
    """A1, L1 have no location (intent); A2 governs line 3."""
    return dict(
        assumptions=[item("A1", "Only completed stays", revision, rationale="Open stays lack a discharge date."),
                     item("A2", "Discharge date marks completion", revision, rationale="Ward convention.",
                          location={"lines": [3, 3]})],
        limitations=[item("L1", "Monthly grain only", revision, rationale="Source has no daily data.")],
    )


def carried(it, revision, **over):
    d = dict(it, confirmed_revision=it["confirmed_revision"], carried_from_revision=revision - 1)
    d.update(over)
    return d


def fresh(it, revision, **over):
    d = dict(it, confirmed_revision=revision, confirmed_at="2026-09-28T00:00:00Z")
    d.pop("carried_from_revision", None)
    d.pop("carried_basis", None)
    d.update(over)
    return d


def candidate(it, **over):
    d = {k: it[k] for k in ("id", "text", "rationale", "location")}
    d["status"] = "candidate"
    d.update(over)
    return d


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.p = Project(self.tmp.name)
        self.sql = self.p.sql("q.sql", SQL_V1)
        self.d = self.p.review_dir("q")
        self.draft = self.d / "draft.json"

    def publish(self, doc, *flags, expected=0):
        self.draft.write_text(json.dumps(doc))
        r = run(["publish", *flags, "q", doc["kind"], str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, expected, r.stdout + r.stderr)
        return r

    def carryforward(self, kind, doc):
        self.draft.write_text(json.dumps(doc))
        r = run(["carryforward", "q", kind, str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return json.loads(r.stdout)

    def carryover(self, doc):
        self.draft.write_text(json.dumps(doc))
        r = run(["carryover", "q", str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return json.loads(r.stdout)

    def scope(self, revision, sql=SQL_V1, **over):
        return scope_doc("q", "q.sql", revision=revision, sql_sha256=sha(sql) if sql else None, **over)

    def review(self, revision, sql, **over):
        return review_doc("q", "q.sql", revision=revision, sql_sha256=sha(sql), **over)

    def publish_scope_v1(self, sql=SQL_V1):
        """Bootstrap rev 1; with SQL, bootstrap then copies scope.source.sql."""
        self.v1 = scope_items()
        self.publish(self.scope(1, sql=sql, **self.v1))
        if sql is not None:
            (self.d / "scope.source.sql").write_text(sql)

    @staticmethod
    def basis(rows):
        return {r["id"]: r["basis"] for r in rows}


class ScopeIntentCarry(Base):
    """A scope revision after an SQL edit: unchanged scope items keep their confirmation."""

    def test_unchanged_null_location_items_carry_after_a_code_edit(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.scope(2, sql=CODE_EDIT, assumptions=[candidate(a1), candidate(a2)], limitations=[candidate(l1)])
        out = self.carryforward("scope", draft)
        # A2 governs line 3, which the edit did not touch: it carries on line evidence, as before.
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged", "A2": "lines-unchanged",
                                                    "L1": "intent-unchanged"})
        self.assertEqual(out["carry"][0]["set"], {"status": "confirmed", **WHO, "confirmed_revision": 1,
                                                  "carried_from_revision": 1, "carried_basis": "intent-unchanged"})
        self.assertEqual((out["walk"], out["bulk"]), ([], []))

        sets = {c["id"]: c["set"] for c in out["carry"]}
        doc = self.scope(2, sql=CODE_EDIT, assumptions=[dict(a1, **sets["A1"]), fresh(a2, 2)],
                         limitations=[dict(l1, **sets["L1"])])
        self.publish(doc)
        published = json.loads((self.d / "scope.json").read_text())
        self.assertEqual(published["assumptions"][0]["carried_basis"], "intent-unchanged")
        self.assertEqual(published["assumptions"][0]["confirmed_revision"], 1)

    def test_changed_text_or_rationale_is_walked_and_refused(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        for field, value in [("text", "Only finished stays"), ("rationale", "Reworded.")]:
            with self.subTest(field=field):
                changed = dict(a1, **{field: value})
                out = self.carryforward("scope", self.scope(2, sql=CODE_EDIT, assumptions=[candidate(changed)],
                                                            limitations=[]))
                self.assertEqual(out["carry"], [])
                self.assertIn(field, out["walk"][0]["why"])
                before = (self.d / "scope.json").read_bytes()
                self.publish(self.scope(2, sql=CODE_EDIT,
                                        assumptions=[carried(changed, 2, carried_basis="intent-unchanged"), fresh(a2, 2)],
                                        limitations=[fresh(l1, 2)]), expected=4)
                self.assertEqual((self.d / "scope.json").read_bytes(), before)

    def test_located_scope_item_with_changed_lines_is_still_walked(self):
        self.publish_scope_v1()
        edit = SQL_V1.replace("IS NOT NULL", "IS NOT NULL AND ward <> 'X'")  # line 3
        self.sql.write_text(edit)
        a1, a2 = self.v1["assumptions"]
        out = self.carryforward("scope", self.scope(2, sql=edit, assumptions=[candidate(a1), candidate(a2)],
                                                    limitations=[]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged"})
        self.assertEqual([w["id"] for w in out["walk"]], ["A2"])

    def test_reconfirm_all_refuses_intent_carried_items(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        r = self.publish(self.scope(2, sql=CODE_EDIT,
                                    assumptions=[carried(a1, 2, carried_basis="intent-unchanged"), fresh(a2, 2)],
                                    limitations=[fresh(l1, 2)]), "--reconfirm-all", expected=4)
        self.assertIn("--reconfirm-all", r.stdout + r.stderr)

    def test_carried_basis_must_match_the_evidence(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        r = self.publish(self.scope(2, sql=CODE_EDIT,
                                    assumptions=[carried(a1, 2, carried_basis="sql-unchanged"), fresh(a2, 2)],
                                    limitations=[fresh(l1, 2)]), expected=4)
        self.assertIn("carried_basis", r.stdout + r.stderr)

    def test_carried_basis_on_a_fresh_item_is_invalid(self):
        doc = scope_doc("q", "q.sql", assumptions=[item("A1", "x", 1, carried_basis="intent-unchanged")])
        r = run(["check", "--stdin"], self.p.root, stdin=json.dumps(doc))
        self.assertEqual(r.returncode, 4, r.stdout)
        self.assertIn("carried_basis", r.stdout)

    def test_scope_first_then_sql_carries_null_location_items(self):
        self.sql.unlink()
        self.publish_scope_v1(sql=None)
        self.sql = self.p.sql("q.sql", SQL_V1)
        a1, _ = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        out = self.carryforward("scope", self.scope(2, assumptions=[candidate(a1)], limitations=[candidate(l1)]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged", "L1": "intent-unchanged"})
        sets = {c["id"]: c["set"] for c in out["carry"]}
        self.publish(self.scope(2, assumptions=[dict(a1, **sets["A1"])], limitations=[dict(l1, **sets["L1"])]))


class ScopeFirstCarryOver(Base):
    """Scope published before the SQL existed; analyse's carryover after the SQL is generated."""

    def setUp(self):
        super().setUp()
        self.sql.unlink()
        self.publish_scope_v1(sql=None)
        self.sql = self.p.sql("q.sql", SQL_V1)

    def test_matching_items_carry_over_with_their_new_location(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.review(1, SQL_V1, assumptions=[
            candidate(a1, location={"lines": [2, 3]}), candidate(a2),
            candidate(a1, id="A3", text="Counts are per ward"),
        ], limitations=[candidate(l1)])
        out = self.carryover(draft)
        self.assertTrue(out["scope_before_sql"])
        # the SQL came after the scope: its own list, asked without a recommended option
        self.assertEqual(out["carry_over"], [])
        self.assertEqual(self.basis(out["carry_over_intent"]),
                         {"A1": "scope-before-sql", "A2": "scope-before-sql", "L1": "scope-before-sql"})
        a1_row = next(c for c in out["carry_over_intent"] if c["id"] == "A1")
        self.assertEqual(a1_row["location"], {"lines": [2, 3]})   # listed for the one bulk answer
        self.assertEqual(a1_row["scope_id"], "A1")
        self.assertEqual([w["id"] for w in out["walk"]], ["A3"])

    def test_reworded_items_are_still_walked(self):
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, SQL_V1, assumptions=[candidate(a1, rationale="Changed.")], limitations=[]))
        self.assertEqual((out["carry_over"], out["carry_over_intent"]), ([], []))
        self.assertIn("differs", out["walk"][0]["why"])


class CarryOverLists(Base):
    """carry_over (the SQL under the item is unchanged) vs carry_over_intent (it changed)."""

    def test_code_edit_puts_intent_items_in_their_own_list(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        out = self.carryover(self.review(1, CODE_EDIT, assumptions=[candidate(a1), candidate(a2)], limitations=[]))
        self.assertFalse(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]), {"A2": "lines-unchanged"})
        self.assertEqual(self.basis(out["carry_over_intent"]), {"A1": "intent-unchanged"})

    def test_located_scope_item_whose_lines_changed_is_walked_with_an_accurate_reason(self):
        self.publish_scope_v1()
        edit = SQL_V1.replace("IS NOT NULL", "IS NOT NULL AND ward <> 'X'")  # line 3
        self.sql.write_text(edit)
        _, a2 = self.v1["assumptions"]
        out = self.carryover(self.review(1, edit, assumptions=[candidate(a2)], limitations=[]))
        self.assertIn("draft location", out["walk"][0]["why"])


class HeaderOnlyChange(Base):
    """A comment-only commit that copies the scope into the leading SQL header is not an SQL change."""

    def test_carryover_treats_a_header_only_change_as_unchanged(self):
        self.publish_scope_v1()
        self.sql.write_text(HEADER_ONLY)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.review(1, HEADER_ONLY, assumptions=[candidate(a1), candidate(a2, location={"lines": [3 + N, 3 + N]})],
                            limitations=[candidate(l1, location={"lines": [5 + N, 7 + N]})])
        out = self.carryover(draft)
        self.assertFalse(out["sql_unchanged"])
        self.assertTrue(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]),
                         {"A1": "sql-body-unchanged", "A2": "sql-body-unchanged", "L1": "sql-body-unchanged"})
        self.assertEqual((out["carry_over_intent"], out["walk"]), ([], []))

    def test_header_growth_is_unchanged_too(self):
        framed = "/*\nassumptions:\n  - Only completed stays\n*/\n" + SQL_V1
        self.sql.write_text(framed)
        self.publish_scope_v1(sql=framed)
        self.sql.write_text(HEADER_ONLY)
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, HEADER_ONLY, assumptions=[candidate(a1)], limitations=[]))
        self.assertTrue(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]), {"A1": "sql-body-unchanged"})

    def test_header_plus_code_change_is_a_change(self):
        self.publish_scope_v1()
        edit = HEADER + CODE_EDIT
        self.sql.write_text(edit)
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, edit, assumptions=[candidate(a1)], limitations=[]))
        self.assertFalse(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over_intent"]), {"A1": "intent-unchanged"})

    def test_review_null_location_item_carries_after_a_header_only_change(self):
        v1 = scope_items()
        self.publish(self.review(1, SQL_V1, **v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_text(HEADER_ONLY)
        a1, a2 = v1["assumptions"]
        l1, = v1["limitations"]
        a2_moved = dict(a2, location={"lines": [3 + N, 3 + N]})
        out = self.carryforward("review", self.review(2, HEADER_ONLY, assumptions=[candidate(a1), candidate(a2_moved)],
                                                      limitations=[candidate(l1)]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "sql-body-unchanged", "A2": "lines-unchanged",
                                                    "L1": "sql-body-unchanged"})
        sets = {c["id"]: c["set"] for c in out["carry"]}
        self.publish(self.review(2, HEADER_ONLY, assumptions=[dict(a1, **sets["A1"]), dict(a2_moved, **sets["A2"])],
                                 limitations=[dict(l1, **sets["L1"])]))


NESTED = "/* header\n   see /* nested note */ the ward's rule\n*/\n"

# (name, before, after): only the leading header differs, so the body is unchanged.
SAME = [
    ("header added", SQL_V1, HEADER + SQL_V1),
    ("leading -- lines and blank lines", SQL_V1, "-- generated\n\n--   by query-builder\n\n" + SQL_V1),
    ("two header blocks", "/* a */\n" + SQL_V1, "/* a */\n/* b\n   c */\n\n" + SQL_V1),
    ("CRLF in header lines only", "/* a */\n" + SQL_V1, "/* a\r\n   b */\r\n" + SQL_V1),
    ("CRLF -- header lines", SQL_V1, "-- a\r\n-- b \r\n" + SQL_V1),
]

# Real changes (or undecidable headers): the body must count as changed.
CHANGED = [
    ("nested header, literal edit", NESTED + "SELECT * FROM t\nWHERE note = 'a -- x'\n  AND ward = 1;\n",
     NESTED + "SELECT * FROM t\nWHERE note = 'a -- y'\n  AND ward = 1;\n"),
    ("nested header edited", "/* a /* b */ c */\nSELECT 1;\n", "/* a /* b */ d */\nSELECT 1;\n"),
    ("code after a nested header", "/* a /* b */ -- */ SELECT 1\nFROM t;\n", "/* a /* b */ -- */ SELECT 2\nFROM t;\n"),
    ("T-SQL ]] escape with --", "SELECT [a]] -- x] FROM t;\n", "SELECT [a]] -- y] FROM t;\n"),
    ("-- inside [ident]", "SELECT [a--b] FROM t;\n", "SELECT [a--c] FROM t;\n"),
    ("escaped '' with --", "SELECT 'it''s -- x' FROM t;\n", "SELECT 'it''s -- y' FROM t;\n"),
    ("Postgres E'\\'' with --", "SELECT E'it\\'s -- x' FROM t;\n", "SELECT E'it\\'s -- y' FROM t;\n"),
    ("Postgres $$ with --", "SELECT $$ a -- x $$;\n", "SELECT $$ a -- y $$;\n"),
    ("MySQL 1--1", "SELECT 1--1;\n", "SELECT 1--2;\n"),
    ("CRLF inside a multi-line literal", "SELECT 'a\nb' FROM t;\n", "SELECT 'a\r\nb' FROM t;\r\n"),
    ("blank line inside a multi-line literal", "SELECT 'a\nb' AS x\nFROM t;\n", "SELECT 'a\n\nb' AS x\nFROM t;\n"),
    ("whitespace in a literal", "SELECT 'a b';\n", "SELECT 'a  b';\n"),
    ("whitespace in [ident]", "SELECT [a b] FROM t;\n", "SELECT [a  b] FROM t;\n"),
    ('whitespace in "ident"', 'SELECT "a b";\n', 'SELECT "a  b";\n'),
    ("comment markers in literals", "SELECT '-- a' AS x, '/* b */' AS y\nFROM t;\n",
     "SELECT '-- changed' AS x, '/* b */' AS y\nFROM t;\n"),
    ("comment edit after the first code line", "SELECT 1 -- a\nFROM t;\n", "SELECT 1 -- b\nFROM t;\n"),
    ("block comment added in the body", "SELECT a, b\nFROM t;\n", "SELECT a, /* kept */ b\nFROM t;\n"),
    ("trailing whitespace in the body", "SELECT 1\nFROM t;\n", "SELECT 1  \nFROM t;\n"),
    ("blank line added in the body", "SELECT 1\nFROM t;\n", "SELECT 1\n\nFROM t;\n"),
    ("@extract marker renamed", "-- @extract: cohort\nSELECT 1;\n", "-- @extract: cohort_v2\nSELECT 1;\n"),
    ("@extract marker spacing", "--  @extract: a\nSELECT 1;\n", "-- @extract: a\nSELECT 1;\n"),
    ("@extract inside a header block", "/*\n-- @extract: a\n*/\nSELECT 1;\n", "/*\n-- @extract: b\n*/\nSELECT 1;\n"),
    ("header edit with code after */", "/* h1 */ SELECT 1;\n", "/* h2 */ SELECT 1;\n"),
    ("unterminated header", "/* x\nSELECT 1;\n", "/* y\nSELECT 1;\n"),
    # a lone CR is a line break to databases and editors, but not to awk
    ("lone CR in a leading -- line", "-- h\rSELECT 1\r", "-- h\rSELECT 2\r"),
    ("lone CR after a block and --", "/* a */ -- b\rDROP TABLE x;\nSELECT 1\n",
     "/* a */ -- b\rDROP TABLE y;\nSELECT 1\n"),
    ("lone CR after a closing */", "/* a\n*/\rSELECT 1;\n", "/* a\n*/\rSELECT 2;\n"),
    ("@extract on a block's opening line", "/* @extract: a */\nSELECT 1;\n", "/* @extract: b */\nSELECT 1;\n"),
    ("MySQL executable comment", "/*!40101 SET x = 1 */;\nSELECT 1;\n", "/*!40101 SET x = 2 */;\nSELECT 1;\n"),
    ("optimiser hint", "/*+ INDEX(t a) */\nSELECT 1;\n", "/*+ INDEX(t b) */\nSELECT 1;\n"),
]


class BodyComparison(Base):
    """Only the leading comment header is ignored; everything after it is compared byte for byte."""

    def verdict(self, before, after, env=None):
        v1 = scope_items()
        self.sql.write_bytes(before.encode())
        self.publish(self.review(1, before, **v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_bytes(after.encode())
        a1 = v1["assumptions"][0]
        self.draft.write_text(json.dumps(self.review(2, after, assumptions=[candidate(a1)], limitations=[])))
        r = run(["carryforward", "q", "review", str(self.draft)], self.p.root, env=env)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return json.loads(r.stdout)

    def fresh_project(self):
        self.setUp()

    def test_header_only_changes_are_unchanged(self):
        for name, before, after in SAME:
            with self.subTest(name):
                self.fresh_project()
                out = self.verdict(before, after)
                self.assertTrue(out["sql_body_unchanged"])
                self.assertEqual(self.basis(out["carry"]), {"A1": "sql-body-unchanged"})

    def test_real_changes_and_odd_headers_are_changes(self):
        for name, before, after in CHANGED:
            with self.subTest(name):
                self.fresh_project()
                out = self.verdict(before, after)
                self.assertFalse(out["sql_body_unchanged"])
                self.assertEqual(out["carry"], [])
                self.assertEqual([b["id"] for b in out["bulk"]], ["A1"])

    def test_hidden_code_edits_cannot_be_published_as_carried(self):
        cases = {name: (before, after) for name, before, after in CHANGED}
        for name in ("nested header, literal edit", "lone CR in a leading -- line", "lone CR after a block and --"):
            with self.subTest(name):
                self.fresh_project()
                before, after = cases[name]
                out = self.verdict(before, after)
                self.assertEqual(out["carry"], [])
                a1 = scope_items()["assumptions"][0]
                forged = carried(a1, 2, carried_basis="sql-body-unchanged")
                r = self.publish(self.review(2, after, assumptions=[forged], limitations=[]), expected=4)
                self.assertIn("A1", r.stdout + r.stderr)

    def test_a_failing_normaliser_counts_as_a_change(self):
        # awk failing (and printing nothing) for both files must not compare two empty digests.
        stub = Path(self.tmp.name) / "stub-bin"
        stub.mkdir()
        (stub / "awk").write_text("#!/bin/sh\nexit 1\n")
        (stub / "awk").chmod(stat.S_IRWXU)
        env = {"PATH": f"{stub}{os.pathsep}{os.environ['PATH']}"}
        out = self.verdict(SQL_V1, CODE_EDIT, env=env)
        self.assertFalse(out["sql_body_unchanged"])
        self.assertEqual(out["carry"], [])


class ReviewBulk(Base):
    """A review item whose SQL changed under it: one bulk question with its location, never silent."""

    def setUp(self):
        super().setUp()
        self.v1 = scope_items()
        self.publish(self.review(1, SQL_V1, **self.v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_text(CODE_EDIT)

    def test_unchanged_null_location_items_are_offered_in_bulk(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        out = self.carryforward("review", self.review(2, CODE_EDIT, assumptions=[
            candidate(a1), candidate(a2), candidate(a1, id="A3", text="New item")],
            limitations=[candidate(l1, rationale="Reworded.")]))
        self.assertEqual(self.basis(out["carry"]), {"A2": "lines-unchanged"})
        self.assertEqual(out["bulk"], [{"kind": "assumptions", "id": "A1", "text": a1["text"],
                                        "rationale": a1["rationale"], "location": None,
                                        "why": out["bulk"][0]["why"]}])
        self.assertEqual({w["id"] for w in out["walk"]}, {"A3", "L1"})

    def test_location_added_or_removed_is_bulk_and_shows_the_location(self):
        a1, a2 = self.v1["assumptions"]
        out = self.carryforward("review", self.review(2, CODE_EDIT, assumptions=[
            candidate(a1, location={"lines": [5, 7]}), candidate(a2, location=None)], limitations=[]))
        self.assertEqual(out["carry"], [])
        self.assertEqual({b["id"]: b["location"] for b in out["bulk"]}, {"A1": {"lines": [5, 7]}, "A2": None})
        self.assertTrue(all("location added or removed" in b["why"] for b in out["bulk"]))
        self.assertEqual(out["walk"], [])

    def test_scope_location_added_is_walked_not_bulk(self):
        self.p.write_json("q", "scope.json", scope_doc("q", "q.sql", sql_sha256=sha(CODE_EDIT), **scope_items()))
        a1, _ = self.v1["assumptions"]
        out = self.carryforward("scope", self.scope(2, sql=CODE_EDIT, assumptions=[candidate(a1, location={"lines": [5, 7]})],
                                                    limitations=[]))
        self.assertEqual((out["carry"], out["bulk"]), ([], []))
        self.assertEqual([w["id"] for w in out["walk"]], ["A1"])

    def test_publish_still_refuses_to_carry_a_bulk_item(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        for basis in ("intent-unchanged", "sql-body-unchanged", None):
            with self.subTest(carried_basis=basis):
                over = {"carried_basis": basis} if basis else {}
                r = self.publish(self.review(2, CODE_EDIT, assumptions=[carried(a1, 2, **over), fresh(a2, 2)],
                                             limitations=[fresh(l1, 2)]), expected=4)
                self.assertIn("A1", r.stdout + r.stderr)
        # the bulk answer is a fresh confirmation for this revision
        self.publish(self.review(2, CODE_EDIT, assumptions=[fresh(a1, 2), fresh(a2, 2)], limitations=[fresh(l1, 2)]))


class AnalyseSkillContract(unittest.TestCase):
    """Analyse asks the bulk and intent lists as described (canonical + packaged copies)."""

    def copies(self, rel):
        return [REPO / "skills" / "data-request-analyse" / rel,
                REPO / "plugins" / "data-request" / "skills" / "analyse" / rel,
                REPO / "dist" / "codex" / "plugins" / "data-request" / "skills" / "analyse" / rel]

    def test_skill_points_to_the_carry_reference(self):
        for path in self.copies("SKILL.md"):
            with self.subTest(path=str(path.relative_to(REPO))):
                text = path.read_text()
                for token in ("carry_over_intent", "references/carry.rst", "carried_basis", "bulk: [{kind, id, text, rationale, location"):
                    self.assertIn(token, text)
                self.assertNotIn("have no location, so the SQL change", text)

    def test_reference_states_the_non_inferable_rules(self):
        for path in self.copies("references/carry.rst"):
            with self.subTest(path=str(path.relative_to(REPO))):
                text = " ".join(path.read_text().split())
                for token in ("sql-body-unchanged", "scope-before-sql", "intent-unchanged", "``location`` lines",
                              "Carry these N forward", "Carry over all (Recommended)", "neither recommended",
                              "summary of the SQL delta", "nested ``/*``", "lone CR",
                              "compares the draft's line numbers"):
                    self.assertIn(token, text)


if __name__ == "__main__":
    unittest.main()
