"""Issue 366: scope items lost their confirmation on any SQL edit because they have no location.

Three failure modes from the field, each driven through the real sqlreview.sh:

* ENQ1213 — a scope revision after an SQL edit re-asked every unchanged `location: null` item.
  A scope item states intent, not SQL lines, so identical id/list/text/rationale carries it
  (basis ``intent-unchanged``); publish still proves the claim and records ``carried_basis``.
* ENQ1205 — scope-first (``sql_sha256: null``, the recommended order): analyse's ``carryover``
  walked every item once the SQL existed. Matching items now carry over (``scope-before-sql``)
  with their new location listed for the one bulk answer.
* ENQ1177 — a comment-only commit copied the scope into the SQL ``/* ... */`` header, so the raw
  SHA changed and nothing carried. A normalised body (comments and blank lines stripped outside
  literals) now counts as unchanged (``sql-body-unchanged``).

Review items with ``location: null`` do NOT carry silently after a real SQL change: they are
offered for one bulk question (``bulk``), and publish still refuses to carry them.

Why the existing tests missed these: ``test_sql_review_carryover.test_without_baseline_nothing
_carries_over`` used a scope without ``sql_sha256`` (the scope-first shape) and pinned "nothing
carries" as intended; ``test_sql_review_carryforward`` used ``LINE_SHIFT`` (a prepended ``--``
comment, i.e. a comment-only change) as its "SQL changed" fixture and asserted the walk.
"""
import hashlib
import json
import tempfile
import unittest

try:  # `unittest discover -s tests` puts tests/ on sys.path; `-m unittest tests.x` does not
    from test_sql_review_scripts import SQL_V1, Project, item, review_doc, run, scope_doc
except ModuleNotFoundError:
    from tests.test_sql_review_scripts import SQL_V1, Project, item, review_doc, run, scope_doc

# SQL_V1, numbered:
#   1 WITH stays AS (            4 )                          7 GROUP BY month;
#   2   SELECT * FROM adm.stays  5 SELECT month, COUNT(*) AS n
#   3   WHERE discharge_date ... 6 FROM stays
CODE_EDIT = SQL_V1.replace("adm.stays", "adm.stays_v2")                  # line 2, executable
HEADER = ("/*\nassumptions:\n  - Only completed stays\n    rationale: Open stays lack a discharge date.\n"
          "limitations:\n  - Monthly grain only\n    consequence: Source has no daily data.\n*/\n")
HEADER_ONLY = HEADER + "-- generated by query-builder\n\n" + SQL_V1.replace(
    "GROUP BY month;", "-- one row per month\nGROUP BY month;  ")        # comments, blanks, trailing space
HEADER_PLUS_CODE = HEADER + CODE_EDIT
N = HEADER_ONLY.count("\n") - SQL_V1.count("\n")                         # lines the comments added before line 7

WHO = {"confirmed_by": "analyst@example", "confirmed_at": "2026-09-15T00:00:00Z"}


def sha(text):
    return hashlib.sha256(text.encode()).hexdigest()


def scope_items(revision=1):
    """A1, L1 have no location (intent); A2 governs line 3."""
    return dict(
        assumptions=[item("A1", "Only completed stays", revision, rationale="Open stays lack a discharge date."),
                     item("A2", "Discharge date marks completion", revision, rationale="Ward convention.",
                          location={"lines": [3, 3]})],
        limitations=[item("L1", "Monthly grain only", revision, rationale="Source has no daily data.")],
    )


def carried(it, revision, **over):
    d = dict(it, confirmed_revision=it["confirmed_revision"], carried_from_revision=revision - 1)
    d.update(over)
    return d


def fresh(it, revision, **over):
    d = dict(it, confirmed_revision=revision, confirmed_at="2026-09-28T00:00:00Z")
    d.pop("carried_from_revision", None)
    d.pop("carried_basis", None)
    d.update(over)
    return d


def candidate(it, **over):
    d = {k: it[k] for k in ("id", "text", "rationale", "location")}
    d["status"] = "candidate"
    d.update(over)
    return d


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.p = Project(self.tmp.name)
        self.sql = self.p.sql("q.sql", SQL_V1)
        self.d = self.p.review_dir("q")
        self.draft = self.d / "draft.json"

    def publish(self, doc, *flags, expected=0):
        self.draft.write_text(json.dumps(doc))
        r = run(["publish", *flags, "q", doc["kind"], str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, expected, r.stdout + r.stderr)
        return r

    def carryforward(self, kind, doc):
        self.draft.write_text(json.dumps(doc))
        r = run(["carryforward", "q", kind, str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return json.loads(r.stdout)

    def carryover(self, doc):
        self.draft.write_text(json.dumps(doc))
        r = run(["carryover", "q", str(self.draft)], self.p.root)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return json.loads(r.stdout)

    def scope(self, revision, sql=SQL_V1, **over):
        return scope_doc("q", "q.sql", revision=revision, sql_sha256=sha(sql) if sql else None, **over)

    def review(self, revision, sql, **over):
        return review_doc("q", "q.sql", revision=revision, sql_sha256=sha(sql), **over)

    def publish_scope_v1(self, sql=SQL_V1):
        """Bootstrap rev 1; with SQL, bootstrap then copies scope.source.sql."""
        self.v1 = scope_items()
        self.publish(self.scope(1, sql=sql, **self.v1))
        if sql is not None:
            (self.d / "scope.source.sql").write_text(sql)

    @staticmethod
    def basis(rows):
        return {r["id"]: r["basis"] for r in rows}


class ScopeIntentCarry(Base):
    """ENQ1213: unchanged scope items keep their confirmation across an SQL edit."""

    def test_unchanged_null_location_items_carry_after_a_code_edit(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.scope(2, sql=CODE_EDIT, assumptions=[candidate(a1), candidate(a2)], limitations=[candidate(l1)])
        out = self.carryforward("scope", draft)
        # A2 governs line 3, which the edit did not touch: it carries on line evidence, as before.
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged", "A2": "lines-unchanged",
                                                    "L1": "intent-unchanged"})
        self.assertEqual(out["carry"][0]["set"], {"status": "confirmed", **WHO, "confirmed_revision": 1,
                                                  "carried_from_revision": 1, "carried_basis": "intent-unchanged"})
        self.assertEqual((out["walk"], out["bulk"]), ([], []))

        sets = {c["id"]: c["set"] for c in out["carry"]}
        doc = self.scope(2, sql=CODE_EDIT, assumptions=[dict(a1, **sets["A1"]), fresh(a2, 2)],
                         limitations=[dict(l1, **sets["L1"])])
        self.publish(doc)
        published = json.loads((self.d / "scope.json").read_text())
        self.assertEqual(published["assumptions"][0]["carried_basis"], "intent-unchanged")
        self.assertEqual(published["assumptions"][0]["confirmed_revision"], 1)

    def test_changed_text_or_rationale_is_walked_and_refused(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        for field, value in [("text", "Only finished stays"), ("rationale", "Reworded.")]:
            with self.subTest(field=field):
                changed = dict(a1, **{field: value})
                out = self.carryforward("scope", self.scope(2, sql=CODE_EDIT, assumptions=[candidate(changed)],
                                                            limitations=[]))
                self.assertEqual(out["carry"], [])
                self.assertIn(field, out["walk"][0]["why"])
                before = (self.d / "scope.json").read_bytes()
                self.publish(self.scope(2, sql=CODE_EDIT,
                                        assumptions=[carried(changed, 2, carried_basis="intent-unchanged"), fresh(a2, 2)],
                                        limitations=[fresh(l1, 2)]), expected=4)
                self.assertEqual((self.d / "scope.json").read_bytes(), before)

    def test_located_scope_item_with_changed_lines_is_still_walked(self):
        self.publish_scope_v1()
        edit = SQL_V1.replace("IS NOT NULL", "IS NOT NULL AND ward <> 'X'")  # line 3
        self.sql.write_text(edit)
        a1, a2 = self.v1["assumptions"]
        out = self.carryforward("scope", self.scope(2, sql=edit, assumptions=[candidate(a1), candidate(a2)],
                                                    limitations=[]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged"})
        self.assertEqual([w["id"] for w in out["walk"]], ["A2"])

    def test_reconfirm_all_refuses_intent_carried_items(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        r = self.publish(self.scope(2, sql=CODE_EDIT,
                                    assumptions=[carried(a1, 2, carried_basis="intent-unchanged"), fresh(a2, 2)],
                                    limitations=[fresh(l1, 2)]), "--reconfirm-all", expected=4)
        self.assertIn("--reconfirm-all", r.stdout + r.stderr)

    def test_carried_basis_must_match_the_evidence(self):
        self.publish_scope_v1()
        self.sql.write_text(CODE_EDIT)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        r = self.publish(self.scope(2, sql=CODE_EDIT,
                                    assumptions=[carried(a1, 2, carried_basis="sql-unchanged"), fresh(a2, 2)],
                                    limitations=[fresh(l1, 2)]), expected=4)
        self.assertIn("carried_basis", r.stdout + r.stderr)

    def test_carried_basis_on_a_fresh_item_is_invalid(self):
        doc = scope_doc("q", "q.sql", assumptions=[item("A1", "x", 1, carried_basis="intent-unchanged")])
        r = run(["check", "--stdin"], self.p.root, stdin=json.dumps(doc))
        self.assertEqual(r.returncode, 4, r.stdout)
        self.assertIn("carried_basis", r.stdout)

    def test_scope_first_then_sql_carries_null_location_items(self):
        self.sql.unlink()
        self.publish_scope_v1(sql=None)
        self.sql = self.p.sql("q.sql", SQL_V1)
        a1, _ = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        out = self.carryforward("scope", self.scope(2, assumptions=[candidate(a1)], limitations=[candidate(l1)]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "intent-unchanged", "L1": "intent-unchanged"})
        sets = {c["id"]: c["set"] for c in out["carry"]}
        self.publish(self.scope(2, assumptions=[dict(a1, **sets["A1"])], limitations=[dict(l1, **sets["L1"])]))


class ScopeFirstCarryOver(Base):
    """ENQ1205: scope published before the SQL existed; analyse's carryover after generation."""

    def setUp(self):
        super().setUp()
        self.sql.unlink()
        self.publish_scope_v1(sql=None)
        self.sql = self.p.sql("q.sql", SQL_V1)

    def test_matching_items_carry_over_with_their_new_location(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.review(1, SQL_V1, assumptions=[
            candidate(a1, location={"lines": [2, 3]}), candidate(a2),
            candidate(a1, id="A3", text="Counts are per ward"),
        ], limitations=[candidate(l1)])
        out = self.carryover(draft)
        self.assertTrue(out["scope_before_sql"])
        self.assertEqual(self.basis(out["carry_over"]),
                         {"A1": "scope-before-sql", "A2": "scope-before-sql", "L1": "scope-before-sql"})
        a1_row = next(c for c in out["carry_over"] if c["id"] == "A1")
        self.assertEqual(a1_row["location"], {"lines": [2, 3]})   # listed for the one bulk answer
        self.assertEqual(a1_row["scope_id"], "A1")
        self.assertEqual([w["id"] for w in out["walk"]], ["A3"])

    def test_reworded_items_are_still_walked(self):
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, SQL_V1, assumptions=[candidate(a1, rationale="Changed.")], limitations=[]))
        self.assertEqual(out["carry_over"], [])
        self.assertIn("differs", out["walk"][0]["why"])


class HeaderOnlyChange(Base):
    """ENQ1177: a comment-only commit (scope copied into the SQL header) is not an SQL change."""

    def test_carryover_treats_a_header_only_change_as_unchanged(self):
        self.publish_scope_v1()
        self.sql.write_text(HEADER_ONLY)
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        draft = self.review(1, HEADER_ONLY, assumptions=[candidate(a1), candidate(a2, location={"lines": [3 + N - 1, 3 + N - 1]})],
                            limitations=[candidate(l1, location={"lines": [11, 13]})])
        out = self.carryover(draft)
        self.assertFalse(out["sql_unchanged"])
        self.assertTrue(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]),
                         {"A1": "sql-body-unchanged", "A2": "sql-body-unchanged", "L1": "sql-body-unchanged"})
        self.assertEqual(out["walk"], [])

    def test_header_growth_is_unchanged_too(self):
        framed = "/*\nassumptions:\n  - Only completed stays\n*/\n" + SQL_V1
        self.sql.write_text(framed)
        self.publish_scope_v1(sql=framed)
        self.sql.write_text(HEADER_ONLY)
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, HEADER_ONLY, assumptions=[candidate(a1)], limitations=[]))
        self.assertTrue(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]), {"A1": "sql-body-unchanged"})

    def test_header_plus_code_change_is_a_change(self):
        self.publish_scope_v1()
        self.sql.write_text(HEADER_PLUS_CODE)
        a1, _ = self.v1["assumptions"]
        out = self.carryover(self.review(1, HEADER_PLUS_CODE, assumptions=[candidate(a1)], limitations=[]))
        self.assertFalse(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry_over"]), {"A1": "intent-unchanged"})

    def test_review_null_location_item_carries_after_a_comment_only_change(self):
        v1 = scope_items()
        self.publish(self.review(1, SQL_V1, **v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_text(HEADER_ONLY)
        a1, a2 = v1["assumptions"]
        l1, = v1["limitations"]
        a2_moved = dict(a2, location={"lines": [3 + N - 1, 3 + N - 1]})
        out = self.carryforward("review", self.review(2, HEADER_ONLY, assumptions=[candidate(a1), candidate(a2_moved)],
                                                      limitations=[candidate(l1)]))
        self.assertEqual(self.basis(out["carry"]), {"A1": "sql-body-unchanged", "A2": "lines-unchanged",
                                                    "L1": "sql-body-unchanged"})
        sets = {c["id"]: c["set"] for c in out["carry"]}
        self.publish(self.review(2, HEADER_ONLY, assumptions=[dict(a1, **sets["A1"]), dict(a2_moved, **sets["A2"])],
                                 limitations=[dict(l1, **sets["L1"])]))


class Normalisation(Base):
    """What the normalised body keeps: anything executable, literals and @extract markers."""

    def verdict(self, before, after):
        v1 = scope_items()
        self.sql.write_text(before)
        self.publish(self.review(1, before, **v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_text(after)
        a1, = v1["assumptions"][:1]
        out = self.carryforward("review", self.review(2, after, assumptions=[candidate(a1)], limitations=[]))
        return out

    def test_comment_markers_inside_literals_are_code(self):
        before = "SELECT '-- a' AS x, '/* b */' AS y\nFROM t;\n"
        after = "SELECT '-- changed' AS x, '/* b */' AS y\nFROM t;\n"
        out = self.verdict(before, after)
        self.assertEqual(out["carry"], [])
        self.assertEqual(out["sql_body_unchanged"], False)

    def test_blank_line_inside_a_multi_line_literal_is_code(self):
        before = "SELECT 'a\nb' AS x\nFROM t;\n"
        after = "SELECT 'a\n\nb' AS x\nFROM t;\n"
        self.assertEqual(self.verdict(before, after)["carry"], [])

    def test_extract_marker_changes_are_code(self):
        before = "-- @extract: cohort\nSELECT 1;\n"
        after = "-- @extract: cohort_v2\nSELECT 1;\n"
        self.assertEqual(self.verdict(before, after)["carry"], [])

    def test_inline_and_block_comments_are_not_code(self):
        before = "SELECT a, b\nFROM t;\n"
        after = "SELECT a, /* kept */ b -- note\nFROM t;\r\n"
        out = self.verdict(before, after)
        self.assertTrue(out["sql_body_unchanged"])
        self.assertEqual(self.basis(out["carry"]), {"A1": "sql-body-unchanged"})


class ReviewBulk(Base):
    """A review `location: null` item after a real SQL change: one bulk question, never silent."""

    def setUp(self):
        super().setUp()
        self.v1 = scope_items()
        self.publish(self.review(1, SQL_V1, **self.v1))
        self.assertEqual(run(["snapshot", "q", "q.sql"], self.p.root).returncode, 0)
        self.sql.write_text(CODE_EDIT)

    def test_unchanged_null_location_items_are_offered_in_bulk(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        out = self.carryforward("review", self.review(2, CODE_EDIT, assumptions=[
            candidate(a1), candidate(a2), candidate(a1, id="A3", text="New item")],
            limitations=[candidate(l1, rationale="Reworded.")]))
        self.assertEqual(self.basis(out["carry"]), {"A2": "lines-unchanged"})
        self.assertEqual([(b["kind"], b["id"]) for b in out["bulk"]], [("assumptions", "A1")])
        self.assertEqual(out["bulk"][0]["text"], a1["text"])
        self.assertEqual(out["bulk"][0]["rationale"], a1["rationale"])
        self.assertEqual({w["id"] for w in out["walk"]}, {"A3", "L1"})

    def test_publish_still_refuses_to_carry_a_bulk_item(self):
        a1, a2 = self.v1["assumptions"]
        l1, = self.v1["limitations"]
        for basis in ("intent-unchanged", None):
            with self.subTest(carried_basis=basis):
                over = {"carried_basis": basis} if basis else {}
                r = self.publish(self.review(2, CODE_EDIT, assumptions=[carried(a1, 2, **over), fresh(a2, 2)],
                                             limitations=[fresh(l1, 2)]), expected=4)
                self.assertIn("A1", r.stdout + r.stderr)
        # the bulk answer is a fresh confirmation for this revision
        self.publish(self.review(2, CODE_EDIT, assumptions=[fresh(a1, 2), fresh(a2, 2)], limitations=[fresh(l1, 2)]))


class AnalyseSkillContract(unittest.TestCase):
    """Analyse names the new bases, the bulk question and keeps --reconfirm-all (canonical + packaged)."""

    def test_analyse_describes_the_new_behaviour(self):
        from pathlib import Path
        repo = Path(__file__).resolve().parent.parent
        for path in (repo / "skills" / "data-request-analyse" / "SKILL.md",
                     repo / "plugins" / "data-request" / "skills" / "analyse" / "SKILL.md",
                     repo / "dist" / "codex" / "plugins" / "data-request" / "skills" / "analyse" / "SKILL.md"):
            with self.subTest(path=str(path.relative_to(repo))):
                text = path.read_text()
                for token in ("sql-body-unchanged", "scope-before-sql", "intent-unchanged", "carried_basis",
                              "bulk:", "Carry these N forward", "--reconfirm-all", "location"):
                    self.assertIn(token, text)


if __name__ == "__main__":
    unittest.main()
