#!/usr/bin/env python3
"""Generate docs/bundles.md from the registry.

`docs/bundles.md` previously listed bundles by hand and rotted the moment the
registry changed (it still advertised the retired `swe`/`infra`/`meta` domain
bundles long after they were regrouped by subject). This is the same metadata-rot
failure mode as #100, so the fix is the same: generate the doc from the single
source of truth and gate it in CI.

The doc depends ONLY on `registry/`, never on upstream skill
frontmatter — so it changes only when a maintainer deliberately edits a bundle,
not on every cosmetic skills sync. That keeps the `--check` gate quiet.

CLI:
    python3 scripts/generate_bundles_doc.py [REPO_ROOT]            # write
    python3 scripts/generate_bundles_doc.py [REPO_ROOT] --check    # fail on drift
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

from _registry import normalize_member

DOC_REL = Path("docs") / "bundles.md"


def _read_yaml(path: Path) -> dict:
    with path.open() as fh:
        return yaml.safe_load(fh) or {}


def _enabled_bundles(repo: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    bundles_dir = repo / "registry" / "bundles"
    for bf in sorted(list(bundles_dir.glob("*.yaml")) + list(bundles_dir.glob("*.yml"))):
        data = _read_yaml(bf)
        claude = (data.get("targets") or {}).get("claude") or {}
        if not claude.get("enabled"):
            continue
        plugin = claude.get("pluginName") or data.get("id") or bf.stem
        leaves = []
        for m in data.get("skills") or []:
            try:
                _src, leaf = normalize_member(m)
            except ValueError:
                continue
            leaves.append(leaf)
        out[plugin] = {
            "description": data.get("description") or "",
            "skills": leaves,
            "agents": list(data.get("agents") or []),
            "mcp": list(data.get("mcp") or []),
            "hooks": list(data.get("hooks") or []),
        }
    return out


def _ordered(order: list[str], enabled: dict) -> list[str]:
    ordered = [p for p in order if p in enabled]
    return ordered + sorted(set(enabled) - set(ordered))


def generate(repo) -> str:
    repo = Path(repo)
    mkt = _read_yaml(repo / "registry" / "marketplace.yaml")
    enabled = _enabled_bundles(repo)
    order = _ordered(list(mkt.get("order") or []), enabled)
    meta = mkt.get("meta") or {}

    lines: list[str] = [
        "---",
        "icon: lucide/package",
        "---",
        "",
        "# Plugins",
        "",
        "<!-- GENERATED by scripts/generate_bundles_doc.py from registry/ — do not edit by hand. -->",
        "",
        "Each **subject** (a tool, library, language, or workflow) is one Claude Code",
        "plugin. Skills are invoked as `/<subject>:<facet>`; agents are delegated as",
        "subagents (auto-routed by their description).",
        "",
        "## Install",
        "",
        "Install the whole set in one command via the `rdl` meta-plugin:",
        "",
        "```bash",
        "/plugin marketplace add nq-rdl/agent-extensions",
    ]
    if meta.get("enabled"):
        lines += [f"/plugin install {meta['name']}@rdl    # installs every subject below"]
    lines += [
        "```",
        "",
        "Or install a single subject:",
        "",
        "```bash",
        "/plugin install <subject>@rdl",
        "```",
        "",
    ]

    for plugin in order:
        b = enabled[plugin]
        lines += ["---", "", f"## {plugin}", "", b["description"].rstrip(".") + ".", ""]
        if b["skills"]:
            lines.append("**Skills**")
            lines.append("")
            for leaf in b["skills"]:
                lines.append(f"- `/{plugin}:{leaf}`")
            lines.append("")
        if b["agents"]:
            lines.append("**Agents**")
            lines.append("")
            for a in b["agents"]:
                lines.append(f"- `{a}` (subagent)")
            lines.append("")
        if b["mcp"]:
            lines.append(f"**MCP server(s):** {', '.join('`' + m + '`' for m in b['mcp'])}")
            lines.append("")
        if b["hooks"]:
            lines.append(f"**Hooks:** {', '.join('`' + h + '`' for h in b['hooks'])}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    do_check = "--check" in argv
    positional = [a for a in argv if not a.startswith("--")]
    repo = Path(positional[0]) if positional else Path(".")
    target = repo / DOC_REL
    expected = generate(repo)
    if do_check:
        actual = target.read_text(encoding="utf-8") if target.is_file() else None
        if actual != expected:
            reason = "missing" if actual is None else "stale"
            print(
                f"::error::{DOC_REL} is {reason} — run "
                "`python3 scripts/generate_bundles_doc.py .`",
                file=sys.stderr,
            )
            return 1
        print(f"{DOC_REL} is in sync.")
        return 0
    target.write_text(expected, encoding="utf-8")
    print(f"  ✓ {DOC_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
