#!/bin/bash
# Regenerate the .gemini/ discovery tree from registry/bundles/*.yaml.
#
# For every bundle with `targets.gemini.enabled: true`:
#   - symlink each skill into  .gemini/skills/<name>  → ../../skills/<name>
#   - symlink each agent into  .gemini/agents/<name>.md → ../../agents/<name>/agent.md
# Rewrites GEMINI.md with generated skills + agents sections.
#
# Idempotent: safe to run repeatedly. Existing symlinks are replaced; stale
# symlinks (for skills/agents no longer enabled) are removed.
#
# Requires: python3 + PyYAML.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

python3 - <<'PY'
import os
import sys
from pathlib import Path
import yaml

REPO = Path(".").resolve()
BUNDLES = sorted((REPO / "registry" / "bundles").glob("*.yaml"))

skills = {}        # skill_name -> set of bundle_ids
agents = {}        # agent_name -> set of bundle_ids
enabled_bundles = []

for bundle_path in BUNDLES:
    with bundle_path.open() as f:
        data = yaml.safe_load(f) or {}
    targets = (data.get("targets") or {}).get("gemini") or {}
    if not targets.get("enabled"):
        continue
    bundle_id = data.get("id") or bundle_path.stem
    enabled_bundles.append((bundle_id, data))
    for s in data.get("skills") or []:
        skills.setdefault(s, set()).add(bundle_id)
    for a in data.get("agents") or []:
        agents.setdefault(a, set()).add(bundle_id)

# Create .gemini structure
gemini_dir = REPO / ".gemini"
skills_dir = gemini_dir / "skills"
agents_dir = gemini_dir / "agents"
skills_dir.mkdir(parents=True, exist_ok=True)
agents_dir.mkdir(parents=True, exist_ok=True)

# Clear existing symlinks that are no longer needed
def wanted_symlinks(d: Path, wanted: set[str]):
    for child in list(d.iterdir()):
        if child.is_symlink() and child.name not in wanted:
            child.unlink()
            print(f"removed stale symlink: {child.relative_to(REPO)}")

wanted_symlinks(skills_dir, set(skills))
wanted_symlinks(agents_dir, {f"{name}.md" for name in agents})

# Create / refresh symlinks
def relink(src: Path, target_rel: str):
    if src.is_symlink() or src.exists():
        src.unlink()
    src.symlink_to(target_rel)
    print(f"linked {src.relative_to(REPO)} -> {target_rel}")

for skill in sorted(skills):
    source_dir = REPO / "skills" / skill
    if not source_dir.exists():
        print(f"::error::Skill source missing: skills/{skill}", file=sys.stderr)
        sys.exit(1)
    relink(skills_dir / skill, f"../../skills/{skill}")

for agent in sorted(agents):
    source_file = REPO / "agents" / agent / "agent.md"
    if not source_file.exists():
        print(f"::error::Agent source missing: agents/{agent}/agent.md", file=sys.stderr)
        sys.exit(1)
    relink(agents_dir / f"{agent}.md", f"../../agents/{agent}/agent.md")

# Regenerate GEMINI.md
lines = [
    "# nq-rdl Agent Extensions",
    "",
    "Curated agent skills and subagents for Gemini CLI.",
    "",
    f"Provides {len(skills)} skills and {len(agents)} subagents across {len(enabled_bundles)} bundles.",
    "",
    "<!-- GENERATED by scripts/generate-gemini-extension.sh — edit the registry or agent/skill sources, then regenerate. -->",
    "",
    "## Bundles",
    "",
]
for bundle_id, data in sorted(enabled_bundles, key=lambda p: p[0]):
    display = data.get("displayName") or bundle_id
    desc = data.get("description") or ""
    lines.append(f"### {bundle_id} — {display}")
    lines.append("")
    if desc:
        lines.append(desc)
        lines.append("")
    bundle_skills = data.get("skills") or []
    bundle_agents = data.get("agents") or []
    if bundle_skills:
        lines.append(f"**Skills**: {', '.join(bundle_skills)}")
        lines.append("")
    if bundle_agents:
        lines.append(f"**Agents**: {', '.join(bundle_agents)}")
        lines.append("")

lines.append("## Usage")
lines.append("")
lines.append("Skills activate automatically when the model identifies a relevant task. Each skill's `SKILL.md` defines its trigger conditions.")
lines.append("")
lines.append("Agents are delegatable subagents: the model routes tasks to them based on the `description` field in each agent's frontmatter. See each agent's file under `agents/` for its exact tool allowlist and system prompt.")
lines.append("")

(REPO / "GEMINI.md").write_text("\n".join(lines))
print(f"wrote GEMINI.md ({len(skills)} skills, {len(agents)} agents, {len(enabled_bundles)} bundles)")
PY

echo ""
echo "Done. Run 'bash scripts/validate-plugins.sh' to verify."
